---
title: "dowel comparison"
output:
  html_document: default
---

# Libraries:

```{r message=FALSE}

library(dplyr)
library(readr)
library(lme4)
library(ggplot2)

```

# Load data:

```{r message=FALSE}

nodowels <- read_csv("../data/raw/1019pumpdata.csv")

nodowels_new <- read_csv("../data/raw/0321pumpdata.csv")

dowels <- read_csv("../data/raw/1115pumpdata.csv")

```

# Tidy data:

```{r}

nodowels_2 <- nodowels %>%
  select(t = `Sample Time (s)`, mvc = `mass volume concentration (ppm)`) %>%
  mutate(run = "no dowels 1") %>%
  filter(t < 7000)

nodowels_new_2 <- nodowels_new %>%
  select(t = `Time (s)`, mvc = `mass volume concentration (ppm)`) %>%
  mutate(run = "no dowels 2") %>%
  filter(mvc < 90)

dowels2 <- dowels %>%
  mutate(`Sample Time` = if_else(`time series` > 2,
                                 (`time series` - 3)*300 + 330,
                                 as.numeric(`Sample Time`)),
         run = "dowels") %>%
  filter(`Sample Time` < 7000) %>%
  select(t = `Sample Time`, mvc = `mass volume concentration (ppm)`, run)

tidy <- rbind(nodowels_2, nodowels_new_2, dowels2)

```


# Initial data plot (simple):

```{r}

tidy %>%
  ggplot(aes(x = t, y = mvc, color = run, group = paste(t, run))) +
  geom_jitter(width = 50)

```


# Model:

no dowels:

```{r}

ndm1 <- tidy %>%
  filter(run == "no dowels 1") %>%
  lm(log(mvc) ~ t, data = .)

summary(ndm1)

ndm2 <- tidy %>%
  filter(run == "no dowels 2") %>%
  lm(log(mvc) ~ t, data = .)

summary(ndm2)
  
```

dowels:

```{r}

ydm <- tidy %>%
  filter(run == "dowels") %>%
  lm(log(mvc) ~ t, data = .)

summary(ydm)

```

# Graph with models overlaid

```{r}

tidy %>%
  ggplot(aes(x = t, y = mvc, color = run, group = t)) +
  geom_point(alpha = .2) +
  stat_function(fun = function(x) exp(coef(ndm1)[1]+coef(ndm1)[2]*x), color = "blue", size = 0.05) +
  stat_function(fun = function(x) exp(coef(ndm2)[1]+coef(ndm2)[2]*x), color = "green", size = 0.05) +
  stat_function(fun = function(x) exp(coef(ydm)[1]+coef(ydm)[2]*x), color = "red", size = 0.05) +
  xlim(c(0,NA)) +
  scale_color_manual(values = c("red", "blue", "green"))

```

```{r eval=F}

dowelsjan <- read_csv("../data/raw/0131pumpdata.csv")[,1:12] %>%
  mutate(run = "old dowels")

dowelsmar <- mutate(nodowels_new, run = "no dowels")

laberror <- rbind(dowelsmar, dowelsjan) %>%
  mutate(t = factor(`Time (s)`), mvc = `mass volume concentration (ppm)`,
         team = paste0(Initials, Initials_1, Initials_2)) %>%
  filter(mvc<80, !is.na(t))

summary(lm(data = laberror, `Volume (mL)` ~ Initials))

summary(lm(data = laberror, `Filter Weight (mg)` ~ Initials_1))

summary(lmer(data = laberror, `Filter+Sediment Weight (mg)` ~ Initials_2 + (1|t) + (1|run)))

summary(lmer(data = laberror, log(mvc) ~ Initials + Initials_1 + Initials_2 + (1|t) + (1|run)))

summary(lmer(data = filter(laberror, run == "old dowels"), log(mvc) ~ Initials + Initials_1 + Initials_2 + (1|t)))

summary(lmer(data = filter(laberror, run == "no dowels"), log(mvc) ~ Initials + Initials_1 + Initials_2 + (1|t)))

```

