---
title: "pumpdata"
output: html_document
---

### run date: 9/20

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


libs
```{r include=FALSE}

library(tidyverse)
require(broom)

```


load data
```{r include=FALSE}

data <- read_csv("../data/raw/928pumpdata.csv")

data

```

tidy data
```{r}

tidy <- data %>%
  filter(!is.na(`mass volume concentration (ppm)`), `time series 5*(n-1)`>1, `mass volume concentration (ppm)`>0) %>%
  rename(mvc = `mass volume concentration (ppm)`,
         seq = `time series 5*(n-1)`,
         loc = Location,
         ht = Height) %>%
  mutate(t = 300*(seq-1), ht_loc = paste0(ht, loc), mvc = as.numeric(mvc)) %>% #bottles were collected every five minutes)
  select(t, everything()) 
tidy
```


multiple regression
```{r}

model <- lm(mvc ~ log(t) + loc + ht, data = tidy)
summary(model)

```
for the sep 20 data, this demonstrates that time is the only significant factor, hence we simplify:

time-only exponential regression
```{r}

model <- lm(log(mvc) ~ t, data = tidy)
summary(model)

```

I accidentally found that a power-law model has a better fit:
```{r}
powerlaw <- lm(log(mvc)~log(t), data = tidy)
summary(powerlaw)
```



plot data

```{r}

tidy %>%
  ggplot(aes(t,mvc)) +
  geom_point() +
  stat_function(fun = function (t) exp(tidy(model)$estimate[1] + tidy(model)$estimate[2]*t), color = "blue") +
  #stat_function(fun = function (t) exp(tidy(powerlaw)$estimate[1] + tidy(powerlaw)$estimate[2]*log(t)), color = "red") +
  ylab("total sediment concentration (ppm)") +
  xlab("time (seconds)")
  
```

